### ISSUE TITLE
running via docker-compose created DB tables, but has a generic Tomcat site via http.

### ISSUE THREAD

**Issue by mabushey** [mihaics/opengts#4]
I get a generic `Apache Tomcat/8.0.35` page.

```
  opengts:
    image: mcsaky/opengts
    container_name: opengts
    restart: unless-stopped
    environment:
            #  - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DBNAME=gts
      - MYSQL_DBPASS=[redacted]
      - MYSQL_DBUSER=map
      - CREATE_DATABASE=false
      - SYSADMIN_PASSWORD=[redacted]
      - MYSQL_SERVICE_HOST=mysql.mir
      - VIRTUAL_HOST=maps.mir
```
The VIRTUAL_HOST is the the jwilder proxy and that part is working as I get the Tomcat page.

```
mysql> show tables;
+---------------+
| Tables_in_gts |
+---------------+
| Account       |
| AccountString |
| Device        |
| DeviceGroup   |
| DeviceList    |
| Diagnostic    |
| Driver        |
| EventData     |
| EventTemplate |
| Geozone       |
| GroupList     |
| PendingPacket |
| Property      |
| Resource      |
| Role          |
| RoleAcl       |
| StatusCode    |
| SystemProps   |
| Transport     |
| UniqueXID     |
| User          |
| UserAcl       |
+---------------+
22 rows in set (0.01 sec)
```
